# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  HELLO: sayhello
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    runs-on: ubuntu-latest
    outputs:
      checkFile: ${{ steps.check1.outputs.isUpdated }}
      checkDir: ${{ steps.check2.outputs.isUpdated }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check1
        name: Checking Changes in package.json
        run: |
          if ${{ github.event_name == 'pull_request' }}
            then
              isChanged=$(git diff --name-only HEAD^ HEAD change-dir/file.txt)
            else
              isChanged=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} change-dir/file.txt)
          fi
          if [ -z "${isChanged}" ]
            then
              echo "isUpdated=no" >> "$GITHUB_OUTPUT"
            else
              echo "isUpdated=yes" >> "$GITHUB_OUTPUT"
          fi

      - id: check2
        name: Checking Changes in server directory
        run: |
          if ${{ github.event_name == 'pull_request' }}
            then
              isChanged=$(git diff --name-only HEAD^ HEAD change-dir/)
            else
              isChanged=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} change-dir/)
          fi
          if [ -z "${isChanged}" ]
            then
              echo "isUpdated=no" >> "$GITHUB_OUTPUT"
            else
              echo "isUpdated=yes" >> "$GITHUB_OUTPUT"
          fi
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs:
      - check
    if: needs.check.checkDir == "yes"
    env:
      IS_FILE_CHANGED: ${{needs.check.outputs.checkFile}}
      IS_DIR_CHANGED: ${{needs.check.outputs.checkDir}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        name: Git Check Out

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "FILE"
          echo $IS_FILE_CHANGED
          echo ${{ needs.check.outputs.checkFile }}
          echo "DIR"
          echo $IS_DIR_CHANGED
          echo ${{ needs.check.outputs.checkDir }}